### ISSUE TITLE
官方文档文案错误

### ISSUE THREAD

**Issue by LinSky** [alovajs/alovajs.github.io#2]
问题：
概览》安装/使用》引入 fetch adapter 中有一文案错误：
“你可以通过window.GlobalFetch使用，它将使用winfow.fetch进行请求。” 中的winfow.fetch中单词window拼写错误

重现步骤
打开链接 https://alova.js.org/zh-CN/overview/installation/
找到 “引入 fetch adapter ”章节

**Comment by JOU-amjs** [comment]
已经修改了，感谢你~

**Comment by LinSky** [comment]
极致效率啊👍

**Comment by JOU-amjs** [comment]
坐在电脑前发呆啊~顺便改了😎
